### ISSUE TITLE
ENOENT: no such file or directory, scandir '.open-next/...'

### ISSUE THREAD

**Issue by Bathilde** [sst/open-next#401]
I have a nextJS application that was working well until yesterday.

Now during my test deployment phase (`npx sst deploy --stage test`), I have the `ENOENT error, where '.open-next/assets' is missing`. This is only happening when I tried to build from gitlab, and if I try to run the command from my mac, it is perfectly working.

Note that I had a build 2h before perfectly working, and I relaunched it, it is now failing....with a similar error:
`ENOENT: no such file or directory, open '.next/routes-manifest.json'`

What could be the reason ? Is there any cache I could remove to retry ?

Thank you.

**Comment by khuezy** [comment]
First thing I'd check is the OS and runtime of the gitlab action. That might explain this weird behavior.
I don't use GitLab but check if there's a button somewhere to delete cache?

**Comment by Bathilde** [comment]
I don't have access to the machine directly, everything is controlled through a yml file containing the instructions. In my case I have the following instructions:

```
    - npm install
    - npm run build
    - npx sst telemetry disable
    - npx sst deploy --stage test
```

**Comment by conico974** [comment]
Try removing `.next` and `.open-next`, there must be some kind of cache on the gitlab server

**Comment by khuezy** [comment]
Does GitLab CI/CD action configuration let you configure the OS and node runtime? I'm assuming it does. Can you share the rest of the yml file?

**Comment by bneilz** [comment]
I'm working with Bathilde. We run the deploy job with a custom docker image :

````dockerfile
FROM registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

RUN apt-get update
RUN apt install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt update
RUN apt install -y nodejs
RUN apt install gcc g++ make -y
RUN apt install -y python
RUN apt install -y postgresql
RUN apt install -y libpq-dev
````

And here is the Gitlab-CI job :
```
deploy-test:
  stage: deploy
  image: my-repo/sst-nodejs-build:latest
  rules:
  - if: '$CI_COMMIT_REF_NAME != "develop" || $CI_COMMIT_TAG'
    when: manual
  - if: $CI_COMMIT_REF_NAME
  environment:
    name: TEST
  script:
    - npm install
    - npm run build
    - npx sst deploy --stage test
 ```
